# AnalystBot Testing

In [1]:
import sys
sys.path.append('../')
import os 
from services.DataAnalysisFlow.DataAnalyst import DataAnalysisFlow

from dotenv import load_dotenv
load_dotenv('../.env')

import boto3
import base64
import io
from PIL import Image

bedrock_client = boto3.client(service_name='bedrock-runtime')

AnalystBot = DataAnalysisFlow(
    llm_client=bedrock_client,
    bedrock_model_id=os.environ['CLAUDE_MODEL_ID'],
    data_directory='../services/DataAnalysisFlow/data/',
    forecast_api_url='http://localhost:8000/forecast/'
    )

print(AnalystBot.available_datasets)

def display_response(response):
    if 'text' in response:
        print('Respuesta en texto:', response['text'])
    
    if 'data' in response:
        print('Datos:')
        display(response['data'])
    
    if 'images' in response and response['images']:
        print('Gráfica:')
        for image in response['images']:
            image_bytes = base64.b64decode(image.split(',')[1])
            img = Image.open(io.BytesIO(image_bytes))
            display(img)
    if 'error' in response:
        print('Error:', response['error'])

    if 'plan' in response:
        print('Plan:', response['plan'])

    if 'generated_code' in response:
        print('Código generado:', response['generated_code'])

{'antiguedad_de_saldos_mexico_31.07.2024': {'path': '..\\services\\DataAnalysisFlow\\data\\antiguedad_de_saldos_mexico_31.07.2024.csv', 'shape': (6642, 25), 'dtypes': {'CIA': 'int64', 'TIPO': 'int64', 'CLIENTE': 'int64', 'NOMBRE_CTE': 'object', 'RFC': 'object', 'VENDEDOR': 'int64', 'NOMBRE_VENDEDOR': 'object', 'TIPO_DCTO.': 'object', 'DOCUMENTO': 'int64', 'PREFIJO': 'object', 'FECHA_FACTURA': 'int64', 'FECHA_VENCIMIENTO': 'int64', 'PREFIJO2': 'object', 'IMPORTE_TRANSACCION': 'float64', 'SALDO_TRANSACCION': 'float64', 'IMPORTE_MXN': 'float64', 'SALDO_MXN': 'float64', 'SDO_X_VENC': 'float64', 'IMP_1_30': 'float64', 'IMP_31_60': 'float64', 'IMP_61_90': 'float64', 'IMP_91_120': 'float64', 'IM_121_150': 'float64', 'IMP_361MAS': 'float64', 'UUID': 'object'}, 'columns': ['CIA', 'TIPO', 'CLIENTE', 'NOMBRE_CTE', 'RFC', 'VENDEDOR', 'NOMBRE_VENDEDOR', 'TIPO_DCTO.', 'DOCUMENTO', 'PREFIJO', 'FECHA_FACTURA', 'FECHA_VENCIMIENTO', 'PREFIJO2', 'IMPORTE_TRANSACCION', 'SALDO_TRANSACCION', 'IMPORTE_MXN', 'SALDO_MXN', 'SDO_X_VENC', 'IMP_1_30', 'IMP_31_60', 'IMP_61_90', 'IMP_91_120', 'IM_121_150', 'IMP_361MAS', 'UUID'], 'head': {'CIA': {0: 10, 1: 10, 2: 10, 3: 10}, 'TIPO': {0: 3, 1: 3, 2: 3, 3: 3}, 'CLIENTE': {0: 108123, 1: 108122, 2: 108122, 3: 108118}, 'NOMBRE_CTE': {0: 'LABORATORIOS PORTUGAL SRL', 1: 'PROBIOMED SA DE CV', 2: 'PROBIOMED SA DE CV', 3: 'PROBIOMED SA DE CV'}, 'RFC': {0: '201002043330', 1: 'PRO780201IDA', 2: 'PRO780201IDA', 3: 'PRO780201IDA'}, 'VENDEDOR': {0: 888, 1: 888, 2: 888, 3: 888}, 'NOMBRE_VENDEDOR': {0: 'VENTA DIRECTA', 1: 'VENTA DIRECTA', 2: 'VENTA DIRECTA', 3: 'VENTA DIRECTA'}, 'TIPO_DCTO.': {0: 'RI', 1: 'RI', 2: 'RI', 3: 'RI'}, 'DOCUMENTO': {0: 11444, 1: 230736, 2: 230021, 3: 230737}, 'PREFIJO': {0: 'SI', 1: '10', 2: '10', 3: '10'}, 'FECHA_FACTURA': {0: 20231220, 1: 20240730, 2: 20240715, 3: 20240730}, 'FECHA_VENCIMIENTO': {0: 20240319, 1: 20240829, 2: 20240814, 3: 20240829}, 'PREFIJO2': {0: 'SI', 1: '10', 2: '10', 3: '10'}, 'IMPORTE_TRANSACCION': {0: 230000.0, 1: 1076383.6, 2: 21961430.49, 3: 52770.34}, 'SALDO_TRANSACCION': {0: 137909.99, 1: 1076383.6, 2: 21961430.49, 3: 52770.34}, 'IMPORTE_MXN': {0: 3892060.0, 1: 1076383.6, 2: 21961430.49, 3: 973480.85}, 'SALDO_MXN': {0: 2333712.85, 1: 1076383.6, 2: 21961430.49, 3: 973480.85}, 'SDO_X_VENC': {0: nan, 1: 1076383.6, 2: 21961430.49, 3: 973480.85}, 'IMP_1_30': {0: nan, 1: nan, 2: nan, 3: nan}, 'IMP_31_60': {0: nan, 1: nan, 2: nan, 3: nan}, 'IMP_61_90': {0: nan, 1: nan, 2: nan, 3: nan}, 'IMP_91_120': {0: nan, 1: nan, 2: nan, 3: nan}, 'IM_121_150': {0: 2333712.85, 1: nan, 2: nan, 3: nan}, 'IMP_361MAS': {0: nan, 1: nan, 2: nan, 3: nan}, 'UUID': {0: nan, 1: '44B7AEE9-0BFB-9344-AA66-20184E1135B5', 2: '84BC8BA0-5655-6C4B-A010-0184D5757F7C', 3: '01092507-9439-504B-B888-92904711AF16'}}}, 'Facturacion': {'path': '..\\services\\DataAnalysisFlow\\data\\Facturacion.csv', 'shape': (29648, 37), 'dtypes': {'Cliente': 'int64', 'Monto Original': 'float64', 'Año': 'int64', 'Mes': 'int64', 'Dia': 'int64', 'Liberacion': 'object', 'Vendedor': 'int64', 'Saldo Remanente': 'float64', 'Numero Ultima Linea': 'int64', 'Descuento Aplicado': 'int64', 'Numero de Compañia': 'int64', 'Fecha de vencimiento de la Factura': 'object', 'Numero de cliente corporativo': 'int64', 'Remanente en moneda base': 'float64', 'Codigo de moneda': 'object', 'Tasa de conversion de moneda': 'float64', 'Codigo de razon': 'object', 'Importe original': 'float64', 'Monto del impuesto': 'float64', 'Alta tasa impositiva': 'int64', 'Numero de orden de ventas': 'int64', 'Numero de orden de compra del cliente': 'object', 'Tipo de pago': 'object', 'Numero de contador': 'int64', 'Codigo bancario': 'object', 'Numeor de borrador': 'int64', 'Tipo de cambio del cliente': 'float64', 'Fecha de vencimiento de la Factura del usuario': 'object', 'Prefijo del documento': 'object', 'Numero del documento': 'int64', 'Tipo de documento': 'int64', 'Prefijo del documento afectado': 'object', 'ID del contrato de oferta': 'object', 'Numero de referencia de autofactura': 'object', 'Creado por usuario': 'object', 'Fecha de cracion': 'object', 'Creado en el momento': 'int64'}, 'columns': ['Cliente', 'Monto Original', 'Año', 'Mes', 'Dia', 'Liberacion', 'Vendedor', 'Saldo Remanente', 'Numero Ultima Linea', 'Descuento Aplicado', 'Numero de Compañia', 'Fecha de vencimiento de la Factura', 'Numero de cliente corporativo', 'Remanente en moneda base', 'Codigo de moneda', 'Tasa de conversion de moneda', 'Codigo de razon', 'Importe original', 'Monto del impuesto', 'Alta tasa impositiva', 'Numero de orden de ventas', 'Numero de orden de compra del cliente', 'Tipo de pago', 'Numero de contador', 'Codigo bancario', 'Numeor de borrador', 'Tipo de cambio del cliente', 'Fecha de vencimiento de la Factura del usuario', 'Prefijo del documento', 'Numero del documento', 'Tipo de documento', 'Prefijo del documento afectado', 'ID del contrato de oferta', 'Numero de referencia de autofactura', 'Creado por usuario', 'Fecha de cracion', 'Creado en el momento'], 'head': {'Cliente': {0: 50999, 1: 50999, 2: 50999, 3: 50999}, 'Monto Original': {0: -1406.0, 1: -4154.0, 2: -3272.0, 3: -0.01}, 'Año': {0: 2025, 1: 2025, 2: 2025, 3: 2025}, 'Mes': {0: 1, 1: 1, 2: 1, 3: 1}, 'Dia': {0: 9, 1: 9, 2: 9, 3: 9}, 'Liberacion': {0: '03-01-2025', 1: '03-01-2025', 2: '03-01-2025', 3: '03-01-2025'}, 'Vendedor': {0: 100010, 1: 100010, 2: 100010, 3: 100010}, 'Saldo Remanente': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Numero Ultima Linea': {0: 0, 1: 0, 2: 0, 3: 0}, 'Descuento Aplicado': {0: 0, 1: 0, 2: 0, 3: 0}, 'Numero de Compañia': {0: 5, 1: 5, 2: 5, 3: 5}, 'Fecha de vencimiento de la Factura': {0: '03-01-2025', 1: '03-01-2025', 2: '03-01-2025', 3: '03-01-2025'}, 'Numero de cliente corporativo': {0: 50999, 1: 50999, 2: 50999, 3: 50999}, 'Remanente en moneda base': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Codigo de moneda': {0: 'MXN', 1: 'MXN', 2: 'MXN', 3: 'MXN'}, 'Tasa de conversion de moneda': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0}, 'Codigo de razon': {0: 'COBRO', 1: 'COBRO', 2: 'COBRO', 3: 'COBRO'}, 'Importe original': {0: -1406.0, 1: -4154.0, 2: -3272.0, 3: -0.01}, 'Monto del impuesto': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Alta tasa impositiva': {0: 0, 1: 0, 2: 0, 3: 0}, 'Numero de orden de ventas': {0: 0, 1: 0, 2: 0, 3: 0}, 'Numero de orden de compra del cliente': {0: 'AS-02012025-L-LITO', 1: 'AS-02012025-F-LITO', 2: 'AS-02012025-F-LITO', 3: 'AS-02012025-F-LITO'}, 'Tipo de pago': {0: 'C', 1: 'C', 2: 'C', 3: 'C'}, 'Numero de contador': {0: 0, 1: 0, 2: 0, 3: 0}, 'Codigo bancario': {0: 'BBV', 1: 'BBV', 2: 'BBV', 3: 'BBV'}, 'Numeor de borrador': {0: 0, 1: 0, 2: 0, 3: 0}, 'Tipo de cambio del cliente': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0}, 'Fecha de vencimiento de la Factura del usuario': {0: '--0', 1: '--0', 2: '--0', 3: '--0'}, 'Prefijo del documento': {0: '05', 1: '05', 2: '05', 3: '05'}, 'Numero del documento': {0: 33574, 1: 33575, 2: 33575, 3: 33575}, 'Tipo de documento': {0: 0, 1: 0, 2: 0, 3: 0}, 'Prefijo del documento afectado': {0: '05', 1: '05', 2: '05', 3: '05'}, 'ID del contrato de oferta': {0: nan, 1: nan, 2: nan, 3: nan}, 'Numero de referencia de autofactura': {0: nan, 1: nan, 2: nan, 3: nan}, 'Creado por usuario': {0: 'GACCEMER', 1: 'GACCEMER', 2: 'GACCEMER', 3: 'GACCEMER'}, 'Fecha de cracion': {0: '09-01-2025', 1: '09-01-2025', 2: '09-01-2025', 3: '09-01-2025'}, 'Creado en el momento': {0: 112728, 1: 112728, 2: 112758, 3: 112816}}}, 'InventarioGrimann': {'path': '..\\services\\DataAnalysisFlow\\data\\InventarioGrimann.csv', 'shape': (28909, 21), 'dtypes': {'Producto': 'object', 'Descripcion': 'object', 'Almacen': 'object', 'Lote': 'object', 'Tipo de producto': 'object', 'Estatus': 'object', 'Fecha de caducidad': 'object', 'Ubicacion': 'object', 'Existencias': 'float64', 'Unidad de Medida': 'object', 'Asignado': 'float64', 'Disponible': 'float64', 'Ajustes': 'float64', 'Recepciones': 'float64', 'Salidas': 'float64', 'Saldo inical': 'float64', 'DVU': 'float64', 'Costo real': 'float64', 'Costo estandar': 'float64', 'Fecha de recepcion': 'object', 'Fecha de aprobacion': 'object'}, 'columns': ['Producto', 'Descripcion', 'Almacen', 'Lote', 'Tipo de producto', 'Estatus', 'Fecha de caducidad', 'Ubicacion', 'Existencias', 'Unidad de Medida', 'Asignado', 'Disponible', 'Ajustes', 'Recepciones', 'Salidas', 'Saldo inical', 'DVU', 'Costo real', 'Costo estandar', 'Fecha de recepcion', 'Fecha de aprobacion'], 'head': {'Producto': {0: '1606006702', 1: '1606020331', 2: '1507112655', 3: '1642648657'}, 'Descripcion': {0: 'CAJ CRISVI TAB 10 MG C/2 MM', 1: 'CAJ TREDA TAB C/30', 2: 'ETQ EUCALIPTINE SOL 1ML', 3: 'BIFEBRAL COMP 300/100 MG C/12'}, 'Almacen': {0: '24', 1: '24', 2: 'D1', 3: 'S13'}, 'Lote': {0: '2407000248', 1: '2007000431', 2: '2411000156', 3: '503MX019A'}, 'Tipo de producto': {0: 'MP COMPRADA', 1: 'MP COMPRADA', 2: 'MP COMPRADA', 3: 'PT FABRICADO'}, 'Estatus': {0: 'R', 1: 'R', 2: 'A', 3: 'R'}, 'Fecha de caducidad': {0: '19-07-2029', 1: '29-07-2025', 2: '08-11-2025', 3: '30-11-2022'}, 'Ubicacion': {0: 'LOCOBODEGA', 1: 'LOCOBODEGA', 2: 'CD.A.02.58', 3: 'DEVOL'}, 'Existencias': {0: 135.418, 1: 153.6, 2: 2999.968, 3: 53.0}, 'Unidad de Medida': {0: 'MR', 1: 'MR', 2: 'MR', 3: 'PZ'}, 'Asignado': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Disponible': {0: 135.418, 1: 153.6, 2: 2999.968, 3: 53.0}, 'Ajustes': {0: 0.0, 1: 153.6, 2: 0.0, 3: 0.0}, 'Recepciones': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Salidas': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Saldo inical': {0: 135.418, 1: 0.0, 2: 2999.968, 3: 53.0}, 'DVU': {0: nan, 1: nan, 2: nan, 3: 372.0}, 'Costo real': {0: 1020.0, 1: 4092.55831, 2: 24.47361, 3: 18.04164}, 'Costo estandar': {0: 1020.0, 1: 4183.0, 2: 29.48, 3: 17.99}, 'Fecha de recepcion': {0: '26-07-2024', 1: '29-07-2020', 2: '22-11-2024', 3: '05-12-2024'}, 'Fecha de aprobacion': {0: '02-08-2024', 1: '03-08-2020', 2: '26-11-2024', 3: '18-12-2020'}}}, 'InventarioProbiomed': {'path': '..\\services\\DataAnalysisFlow\\data\\InventarioProbiomed.csv', 'shape': (4533, 21), 'dtypes': {'Producto': 'object', 'Descripcion': 'object', 'Almacen': 'object', 'Lote': 'object', 'Tipo de producto': 'object', 'Estatus': 'object', 'Fecha de caducidad': 'object', 'Ubicacion': 'object', 'Existencias': 'float64', 'Unidad de Medida': 'object', 'Asignado': 'float64', 'Disponible': 'float64', 'Ajustes': 'float64', 'Recepciones': 'float64', 'Salidas': 'float64', 'Saldo inical': 'float64', 'DVU': 'float64', 'Costo real': 'float64', 'Costo estandar': 'float64', 'Fecha de recepcion': 'object', 'Fecha de aprobacion': 'object'}, 'columns': ['Producto', 'Descripcion', 'Almacen', 'Lote', 'Tipo de producto', 'Estatus', 'Fecha de caducidad', 'Ubicacion', 'Existencias', 'Unidad de Medida', 'Asignado', 'Disponible', 'Ajustes', 'Recepciones', 'Salidas', 'Saldo inical', 'DVU', 'Costo real', 'Costo estandar', 'Fecha de recepcion', 'Fecha de aprobacion'], 'head': {'Producto': {0: '3111000130', 1: '3117000746', 2: '3117020564', 3: '3101000555'}, 'Descripcion': {0: 'TPO BRBTILO GRIS 13MM ULTRACLEAN', 1: 'FIC ACCE ET 0.45-0.2UM 1.8M2', 2: 'BFF EST PH4', 3: 'ISOPROPANOL HPLC'}, 'Almacen': {0: 'P31', 1: 'P11', 2: 'P11', 3: 'P11'}, 'Lote': {0: '2310000205', 1: '2408000008', 2: '2406000074', 3: '2312000005'}, 'Tipo de producto': {0: 'MP COMPRADA', 1: 'MP COMPRADA', 2: 'MP COMPRADA', 3: 'MP COMPRADA'}, 'Estatus': {0: 'A', 1: 'A', 2: 'A', 3: 'A'}, 'Fecha de caducidad': {0: '24-06-2025', 1: '30-06-2026', 2: '30-06-2028', 3: '30-06-2026'}, 'Ubicacion': {0: 'G-004', 1: 'ATP7T9', 2: 'ATP3T5', 3: 'ATP11T21'}, 'Existencias': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0}, 'Unidad de Medida': {0: 'MR', 1: 'PZ', 2: 'ML', 3: 'ML'}, 'Asignado': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Disponible': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0}, 'Ajustes': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Recepciones': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Salidas': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0}, 'Saldo inical': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0}, 'DVU': {0: nan, 1: nan, 2: nan, 3: nan}, 'Costo real': {0: 686.13668, 1: 12049.52463, 2: 0.48842, 3: 0.19392}, 'Costo estandar': {0: 921.375, 1: 13130.91, 2: 1.66257, 3: 0.20558}, 'Fecha de recepcion': {0: '15-12-2023', 1: '01-08-2024', 2: '18-06-2024', 3: '01-12-2023'}, 'Fecha de aprobacion': {0: '15-12-2023', 1: '02-08-2024', 2: '20-06-2024', 3: '11-12-2023'}}}, 'Maviglin_AC_cleaned': {'path': '..\\services\\DataAnalysisFlow\\data\\Maviglin_AC_cleaned.csv', 'shape': (361, 16), 'dtypes': {'no_lote': 'object', 'area_mezclado': 'object', 'equipo_mezclado': 'object', 'codigo_mezclado': 'object', 'equipo_molienda': 'object', 'codigo_molienda': 'object', 'rendimiento_autorizado_mezclado': 'float64', 'rendimiento_obtenido_mezclado': 'float64', 'inicio_almacenamiento': 'object', 'fin_almacenamiento': 'object', 'tiempo_total_almacenamiento': 'object', 'area_tableteo': 'object', 'equipo_tableteo': 'object', 'codigo_tableteo': 'object', 'rendimiento_autorizado_tableteo': 'float64', 'rendimiento_obtenido_tableteo': 'float64'}, 'columns': ['no_lote', 'area_mezclado', 'equipo_mezclado', 'codigo_mezclado', 'equipo_molienda', 'codigo_molienda', 'rendimiento_autorizado_mezclado', 'rendimiento_obtenido_mezclado', 'inicio_almacenamiento', 'fin_almacenamiento', 'tiempo_total_almacenamiento', 'area_tableteo', 'equipo_tableteo', 'codigo_tableteo', 'rendimiento_autorizado_tableteo', 'rendimiento_obtenido_tableteo'], 'head': {'no_lote': {0: '4A0001', 1: '4A0002', 2: '4A0003', 3: '4A0004'}, 'area_mezclado': {0: 'Mezclado 1', 1: 'Mezclado 1', 2: 'Mezclado 2', 3: 'Mezclado 1'}, 'equipo_mezclado': {0: 'Mezclador Romboidal', 1: 'Mezclador Romboidal', 2: 'Mezclador Romboidal', 3: 'Mezclador Romboidal'}, 'codigo_mezclado': {0: 'MEZ-007-SL-O', 1: 'MEZ-007-SL-O', 2: 'MEZ-006-SL-O', 3: 'MEZ-007-SL-O'}, 'equipo_molienda': {0: 'Molino Quadro 194 con malla de 1.905 mm', 1: 'Molino Quadro 194 con malla de 1.905 mm', 2: 'Molino granulador Hydratec con malla de 1.85 mm', 3: 'Molino Quadro 194 con malla de 1.905 mm'}, 'codigo_molienda': {0: 'MOL-004-SL-O', 1: 'MOL-004-SL-O', 2: 'MOL-002-SL-O', 3: 'MOL-004-SL-O'}, 'rendimiento_autorizado_mezclado': {0: 100.0, 1: 100.0, 2: 100.0, 3: 100.0}, 'rendimiento_obtenido_mezclado': {0: 101.16, 1: 100.8, 2: 101.33, 3: 101.13}, 'inicio_almacenamiento': {0: '2024-01-05', 1: '2024-01-05', 2: '2024-01-05', 3: '2024-01-05'}, 'fin_almacenamiento': {0: '2024-01-05', 1: '2024-01-05', 2: '2024-01-06', 3: '2024-01-08'}, 'tiempo_total_almacenamiento': {0: '12:55:00', 1: '9:20:00', 2: '20:30:00', 3: '62:30:00'}, 'area_tableteo': {0: 'Tableteo 2', 1: 'Tableteo 2', 2: 'Tableteo 2', 3: 'Tableteo 2'}, 'equipo_tableteo': {0: 'Tableteadora Fette 1200i', 1: 'Tableteadora Fette 1200i', 2: 'Tableteadora Fette 1200i', 3: 'Tableteadora Fette 1200i'}, 'codigo_tableteo': {0: 'TAB-001-SL-O', 1: 'TAB-001-SL-O', 2: 'TAB-001-SL-O', 3: 'TAB-001-SL-O'}, 'rendimiento_autorizado_tableteo': {0: 98.0, 1: 98.0, 2: 98.0, 3: 98.0}, 'rendimiento_obtenido_tableteo': {0: 99.81, 1: 99.34, 2: 99.12, 3: 99.57}}}}

In [2]:
available_datasets = AnalystBot.available_datasets
for key, value in available_datasets.items():
    print(key)
    display(value)

antiguedad_de_saldos_mexico_31.07.2024

{'path': '..\\services\\DataAnalysisFlow\\data\\antiguedad_de_saldos_mexico_31.07.2024.csv',
 'shape': (6642, 25),
 'dtypes': {'CIA': 'int64',
  'TIPO': 'int64',
  'CLIENTE': 'int64',
  'NOMBRE_CTE': 'object',
  'RFC': 'object',
  'VENDEDOR': 'int64',
  'NOMBRE_VENDEDOR': 'object',
  'TIPO_DCTO.': 'object',
  'DOCUMENTO': 'int64',
  'PREFIJO': 'object',
  'FECHA_FACTURA': 'int64',
  'FECHA_VENCIMIENTO': 'int64',
  'PREFIJO2': 'object',
  'IMPORTE_TRANSACCION': 'float64',
  'SALDO_TRANSACCION': 'float64',
  'IMPORTE_MXN': 'float64',
  'SALDO_MXN': 'float64',
  'SDO_X_VENC': 'float64',
  'IMP_1_30': 'float64',
  'IMP_31_60': 'float64',
  'IMP_61_90': 'float64',
  'IMP_91_120': 'float64',
  'IM_121_150': 'float64',
  'IMP_361MAS': 'float64',
  'UUID': 'object'},
 'columns': ['CIA',
  'TIPO',
  'CLIENTE',
  'NOMBRE_CTE',
  'RFC',
  'VENDEDOR',
  'NOMBRE_VENDEDOR',
  'TIPO_DCTO.',
  'DOCUMENTO',
  'PREFIJO',
  'FECHA_FACTURA',
  'FECHA_VENCIMIENTO',
  'PREFIJO2',
  'IMPORTE_TRANSACCION',
  'SALDO_TRANSACCION',
  'IMPORTE_MXN',
  'SALDO_MXN',
  'SDO_X_VENC',
  'IMP_1_30',
  'IMP_31_60',
  'IMP_61_90',
  'IMP_91_120',
  'IM_121_150',
  'IMP_361MAS',
  'UUID'],
 'head': {'CIA': {0: 10, 1: 10, 2: 10, 3: 10},
  'TIPO': {0: 3, 1: 3, 2: 3, 3: 3},
  'CLIENTE': {0: 108123, 1: 108122, 2: 108122, 3: 108118},
  'NOMBRE_CTE': {0: 'LABORATORIOS PORTUGAL SRL',
   1: 'PROBIOMED SA DE CV',
   2: 'PROBIOMED SA DE CV',
   3: 'PROBIOMED SA DE CV'},
  'RFC': {0: '201002043330',
   1: 'PRO780201IDA',
   2: 'PRO780201IDA',
   3: 'PRO780201IDA'},
  'VENDEDOR': {0: 888, 1: 888, 2: 888, 3: 888},
  'NOMBRE_VENDEDOR': {0: 'VENTA DIRECTA',
   1: 'VENTA DIRECTA',
   2: 'VENTA DIRECTA',
   3: 'VENTA DIRECTA'},
  'TIPO_DCTO.': {0: 'RI', 1: 'RI', 2: 'RI', 3: 'RI'},
  'DOCUMENTO': {0: 11444, 1: 230736, 2: 230021, 3: 230737},
  'PREFIJO': {0: 'SI', 1: '10', 2: '10', 3: '10'},
  'FECHA_FACTURA': {0: 20231220, 1: 20240730, 2: 20240715, 3: 20240730},
  'FECHA_VENCIMIENTO': {0: 20240319, 1: 20240829, 2: 20240814, 3: 20240829},
  'PREFIJO2': {0: 'SI', 1: '10', 2: '10', 3: '10'},
  'IMPORTE_TRANSACCION': {0: 230000.0,
   1: 1076383.6,
   2: 21961430.49,
   3: 52770.34},
  'SALDO_TRANSACCION': {0: 137909.99,
   1: 1076383.6,
   2: 21961430.49,
   3: 52770.34},
  'IMPORTE_MXN': {0: 3892060.0, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
  'SALDO_MXN': {0: 2333712.85, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
  'SDO_X_VENC': {0: nan, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
  'IMP_1_30': {0: nan, 1: nan, 2: nan, 3: nan},
  'IMP_31_60': {0: nan, 1: nan, 2: nan, 3: nan},
  'IMP_61_90': {0: nan, 1: nan, 2: nan, 3: nan},
  'IMP_91_120': {0: nan, 1: nan, 2: nan, 3: nan},
  'IM_121_150': {0: 2333712.85, 1: nan, 2: nan, 3: nan},
  'IMP_361MAS': {0: nan, 1: nan, 2: nan, 3: nan},
  'UUID': {0: nan,
   1: '44B7AEE9-0BFB-9344-AA66-20184E1135B5',
   2: '84BC8BA0-5655-6C4B-A010-0184D5757F7C',
   3: '01092507-9439-504B-B888-92904711AF16'}}}

Facturacion

{'path': '..\\services\\DataAnalysisFlow\\data\\Facturacion.csv',
 'shape': (29648, 37),
 'dtypes': {'Cliente': 'int64',
  'Monto Original': 'float64',
  'Año': 'int64',
  'Mes': 'int64',
  'Dia': 'int64',
  'Liberacion': 'object',
  'Vendedor': 'int64',
  'Saldo Remanente': 'float64',
  'Numero Ultima Linea': 'int64',
  'Descuento Aplicado': 'int64',
  'Numero de Compañia': 'int64',
  'Fecha de vencimiento de la Factura': 'object',
  'Numero de cliente corporativo': 'int64',
  'Remanente en moneda base': 'float64',
  'Codigo de moneda': 'object',
  'Tasa de conversion de moneda': 'float64',
  'Codigo de razon': 'object',
  'Importe original': 'float64',
  'Monto del impuesto': 'float64',
  'Alta tasa impositiva': 'int64',
  'Numero de orden de ventas': 'int64',
  'Numero de orden de compra del cliente': 'object',
  'Tipo de pago': 'object',
  'Numero de contador': 'int64',
  'Codigo bancario': 'object',
  'Numeor de borrador': 'int64',
  'Tipo de cambio del cliente': 'float64',
  'Fecha de vencimiento de la Factura del usuario': 'object',
  'Prefijo del documento': 'object',
  'Numero del documento': 'int64',
  'Tipo de documento': 'int64',
  'Prefijo del documento afectado': 'object',
  'ID del contrato de oferta': 'object',
  'Numero de referencia de autofactura': 'object',
  'Creado por usuario': 'object',
  'Fecha de cracion': 'object',
  'Creado en el momento': 'int64'},
 'columns': ['Cliente',
  'Monto Original',
  'Año',
  'Mes',
  'Dia',
  'Liberacion',
  'Vendedor',
  'Saldo Remanente',
  'Numero Ultima Linea',
  'Descuento Aplicado',
  'Numero de Compañia',
  'Fecha de vencimiento de la Factura',
  'Numero de cliente corporativo',
  'Remanente en moneda base',
  'Codigo de moneda',
  'Tasa de conversion de moneda',
  'Codigo de razon',
  'Importe original',
  'Monto del impuesto',
  'Alta tasa impositiva',
  'Numero de orden de ventas',
  'Numero de orden de compra del cliente',
  'Tipo de pago',
  'Numero de contador',
  'Codigo bancario',
  'Numeor de borrador',
  'Tipo de cambio del cliente',
  'Fecha de vencimiento de la Factura del usuario',
  'Prefijo del documento',
  'Numero del documento',
  'Tipo de documento',
  'Prefijo del documento afectado',
  'ID del contrato de oferta',
  'Numero de referencia de autofactura',
  'Creado por usuario',
  'Fecha de cracion',
  'Creado en el momento'],
 'head': {'Cliente': {0: 50999, 1: 50999, 2: 50999, 3: 50999},
  'Monto Original': {0: -1406.0, 1: -4154.0, 2: -3272.0, 3: -0.01},
  'Año': {0: 2025, 1: 2025, 2: 2025, 3: 2025},
  'Mes': {0: 1, 1: 1, 2: 1, 3: 1},
  'Dia': {0: 9, 1: 9, 2: 9, 3: 9},
  'Liberacion': {0: '03-01-2025',
   1: '03-01-2025',
   2: '03-01-2025',
   3: '03-01-2025'},
  'Vendedor': {0: 100010, 1: 100010, 2: 100010, 3: 100010},
  'Saldo Remanente': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Numero Ultima Linea': {0: 0, 1: 0, 2: 0, 3: 0},
  'Descuento Aplicado': {0: 0, 1: 0, 2: 0, 3: 0},
  'Numero de Compañia': {0: 5, 1: 5, 2: 5, 3: 5},
  'Fecha de vencimiento de la Factura': {0: '03-01-2025',
   1: '03-01-2025',
   2: '03-01-2025',
   3: '03-01-2025'},
  'Numero de cliente corporativo': {0: 50999, 1: 50999, 2: 50999, 3: 50999},
  'Remanente en moneda base': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Codigo de moneda': {0: 'MXN', 1: 'MXN', 2: 'MXN', 3: 'MXN'},
  'Tasa de conversion de moneda': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0},
  'Codigo de razon': {0: 'COBRO', 1: 'COBRO', 2: 'COBRO', 3: 'COBRO'},
  'Importe original': {0: -1406.0, 1: -4154.0, 2: -3272.0, 3: -0.01},
  'Monto del impuesto': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Alta tasa impositiva': {0: 0, 1: 0, 2: 0, 3: 0},
  'Numero de orden de ventas': {0: 0, 1: 0, 2: 0, 3: 0},
  'Numero de orden de compra del cliente': {0: 'AS-02012025-L-LITO',
   1: 'AS-02012025-F-LITO',
   2: 'AS-02012025-F-LITO',
   3: 'AS-02012025-F-LITO'},
  'Tipo de pago': {0: 'C', 1: 'C', 2: 'C', 3: 'C'},
  'Numero de contador': {0: 0, 1: 0, 2: 0, 3: 0},
  'Codigo bancario': {0: 'BBV', 1: 'BBV', 2: 'BBV', 3: 'BBV'},
  'Numeor de borrador': {0: 0, 1: 0, 2: 0, 3: 0},
  'Tipo de cambio del cliente': {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0},
  'Fecha de vencimiento de la Factura del usuario': {0: '--0',
   1: '--0',
   2: '--0',
   3: '--0'},
  'Prefijo del documento': {0: '05', 1: '05', 2: '05', 3: '05'},
  'Numero del documento': {0: 33574, 1: 33575, 2: 33575, 3: 33575},
  'Tipo de documento': {0: 0, 1: 0, 2: 0, 3: 0},
  'Prefijo del documento afectado': {0: '05', 1: '05', 2: '05', 3: '05'},
  'ID del contrato de oferta': {0: nan, 1: nan, 2: nan, 3: nan},
  'Numero de referencia de autofactura': {0: nan, 1: nan, 2: nan, 3: nan},
  'Creado por usuario': {0: 'GACCEMER',
   1: 'GACCEMER',
   2: 'GACCEMER',
   3: 'GACCEMER'},
  'Fecha de cracion': {0: '09-01-2025',
   1: '09-01-2025',
   2: '09-01-2025',
   3: '09-01-2025'},
  'Creado en el momento': {0: 112728, 1: 112728, 2: 112758, 3: 112816}}}

InventarioGrimann

{'path': '..\\services\\DataAnalysisFlow\\data\\InventarioGrimann.csv',
 'shape': (28909, 21),
 'dtypes': {'Producto': 'object',
  'Descripcion': 'object',
  'Almacen': 'object',
  'Lote': 'object',
  'Tipo de producto': 'object',
  'Estatus': 'object',
  'Fecha de caducidad': 'object',
  'Ubicacion': 'object',
  'Existencias': 'float64',
  'Unidad de Medida': 'object',
  'Asignado': 'float64',
  'Disponible': 'float64',
  'Ajustes': 'float64',
  'Recepciones': 'float64',
  'Salidas': 'float64',
  'Saldo inical': 'float64',
  'DVU': 'float64',
  'Costo real': 'float64',
  'Costo estandar': 'float64',
  'Fecha de recepcion': 'object',
  'Fecha de aprobacion': 'object'},
 'columns': ['Producto',
  'Descripcion',
  'Almacen',
  'Lote',
  'Tipo de producto',
  'Estatus',
  'Fecha de caducidad',
  'Ubicacion',
  'Existencias',
  'Unidad de Medida',
  'Asignado',
  'Disponible',
  'Ajustes',
  'Recepciones',
  'Salidas',
  'Saldo inical',
  'DVU',
  'Costo real',
  'Costo estandar',
  'Fecha de recepcion',
  'Fecha de aprobacion'],
 'head': {'Producto': {0: '1606006702',
   1: '1606020331',
   2: '1507112655',
   3: '1642648657'},
  'Descripcion': {0: 'CAJ CRISVI TAB 10 MG C/2 MM',
   1: 'CAJ TREDA TAB C/30',
   2: 'ETQ EUCALIPTINE SOL 1ML',
   3: 'BIFEBRAL COMP 300/100 MG C/12'},
  'Almacen': {0: '24', 1: '24', 2: 'D1', 3: 'S13'},
  'Lote': {0: '2407000248', 1: '2007000431', 2: '2411000156', 3: '503MX019A'},
  'Tipo de producto': {0: 'MP COMPRADA',
   1: 'MP COMPRADA',
   2: 'MP COMPRADA',
   3: 'PT FABRICADO'},
  'Estatus': {0: 'R', 1: 'R', 2: 'A', 3: 'R'},
  'Fecha de caducidad': {0: '19-07-2029',
   1: '29-07-2025',
   2: '08-11-2025',
   3: '30-11-2022'},
  'Ubicacion': {0: 'LOCOBODEGA', 1: 'LOCOBODEGA', 2: 'CD.A.02.58', 3: 'DEVOL'},
  'Existencias': {0: 135.418, 1: 153.6, 2: 2999.968, 3: 53.0},
  'Unidad de Medida': {0: 'MR', 1: 'MR', 2: 'MR', 3: 'PZ'},
  'Asignado': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Disponible': {0: 135.418, 1: 153.6, 2: 2999.968, 3: 53.0},
  'Ajustes': {0: 0.0, 1: 153.6, 2: 0.0, 3: 0.0},
  'Recepciones': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Salidas': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Saldo inical': {0: 135.418, 1: 0.0, 2: 2999.968, 3: 53.0},
  'DVU': {0: nan, 1: nan, 2: nan, 3: 372.0},
  'Costo real': {0: 1020.0, 1: 4092.55831, 2: 24.47361, 3: 18.04164},
  'Costo estandar': {0: 1020.0, 1: 4183.0, 2: 29.48, 3: 17.99},
  'Fecha de recepcion': {0: '26-07-2024',
   1: '29-07-2020',
   2: '22-11-2024',
   3: '05-12-2024'},
  'Fecha de aprobacion': {0: '02-08-2024',
   1: '03-08-2020',
   2: '26-11-2024',
   3: '18-12-2020'}}}

InventarioProbiomed

{'path': '..\\services\\DataAnalysisFlow\\data\\InventarioProbiomed.csv',
 'shape': (4533, 21),
 'dtypes': {'Producto': 'object',
  'Descripcion': 'object',
  'Almacen': 'object',
  'Lote': 'object',
  'Tipo de producto': 'object',
  'Estatus': 'object',
  'Fecha de caducidad': 'object',
  'Ubicacion': 'object',
  'Existencias': 'float64',
  'Unidad de Medida': 'object',
  'Asignado': 'float64',
  'Disponible': 'float64',
  'Ajustes': 'float64',
  'Recepciones': 'float64',
  'Salidas': 'float64',
  'Saldo inical': 'float64',
  'DVU': 'float64',
  'Costo real': 'float64',
  'Costo estandar': 'float64',
  'Fecha de recepcion': 'object',
  'Fecha de aprobacion': 'object'},
 'columns': ['Producto',
  'Descripcion',
  'Almacen',
  'Lote',
  'Tipo de producto',
  'Estatus',
  'Fecha de caducidad',
  'Ubicacion',
  'Existencias',
  'Unidad de Medida',
  'Asignado',
  'Disponible',
  'Ajustes',
  'Recepciones',
  'Salidas',
  'Saldo inical',
  'DVU',
  'Costo real',
  'Costo estandar',
  'Fecha de recepcion',
  'Fecha de aprobacion'],
 'head': {'Producto': {0: '3111000130',
   1: '3117000746',
   2: '3117020564',
   3: '3101000555'},
  'Descripcion': {0: 'TPO BRBTILO GRIS 13MM ULTRACLEAN',
   1: 'FIC ACCE ET 0.45-0.2UM 1.8M2',
   2: 'BFF EST PH4',
   3: 'ISOPROPANOL HPLC'},
  'Almacen': {0: 'P31', 1: 'P11', 2: 'P11', 3: 'P11'},
  'Lote': {0: '2310000205', 1: '2408000008', 2: '2406000074', 3: '2312000005'},
  'Tipo de producto': {0: 'MP COMPRADA',
   1: 'MP COMPRADA',
   2: 'MP COMPRADA',
   3: 'MP COMPRADA'},
  'Estatus': {0: 'A', 1: 'A', 2: 'A', 3: 'A'},
  'Fecha de caducidad': {0: '24-06-2025',
   1: '30-06-2026',
   2: '30-06-2028',
   3: '30-06-2026'},
  'Ubicacion': {0: 'G-004', 1: 'ATP7T9', 2: 'ATP3T5', 3: 'ATP11T21'},
  'Existencias': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0},
  'Unidad de Medida': {0: 'MR', 1: 'PZ', 2: 'ML', 3: 'ML'},
  'Asignado': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Disponible': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0},
  'Ajustes': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Recepciones': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Salidas': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0},
  'Saldo inical': {0: 276.0, 1: 8.0, 2: 6000.0, 3: 200000.0},
  'DVU': {0: nan, 1: nan, 2: nan, 3: nan},
  'Costo real': {0: 686.13668, 1: 12049.52463, 2: 0.48842, 3: 0.19392},
  'Costo estandar': {0: 921.375, 1: 13130.91, 2: 1.66257, 3: 0.20558},
  'Fecha de recepcion': {0: '15-12-2023',
   1: '01-08-2024',
   2: '18-06-2024',
   3: '01-12-2023'},
  'Fecha de aprobacion': {0: '15-12-2023',
   1: '02-08-2024',
   2: '20-06-2024',
   3: '11-12-2023'}}}

Maviglin_AC_cleaned

{'path': '..\\services\\DataAnalysisFlow\\data\\Maviglin_AC_cleaned.csv',
 'shape': (361, 16),
 'dtypes': {'no_lote': 'object',
  'area_mezclado': 'object',
  'equipo_mezclado': 'object',
  'codigo_mezclado': 'object',
  'equipo_molienda': 'object',
  'codigo_molienda': 'object',
  'rendimiento_autorizado_mezclado': 'float64',
  'rendimiento_obtenido_mezclado': 'float64',
  'inicio_almacenamiento': 'object',
  'fin_almacenamiento': 'object',
  'tiempo_total_almacenamiento': 'object',
  'area_tableteo': 'object',
  'equipo_tableteo': 'object',
  'codigo_tableteo': 'object',
  'rendimiento_autorizado_tableteo': 'float64',
  'rendimiento_obtenido_tableteo': 'float64'},
 'columns': ['no_lote',
  'area_mezclado',
  'equipo_mezclado',
  'codigo_mezclado',
  'equipo_molienda',
  'codigo_molienda',
  'rendimiento_autorizado_mezclado',
  'rendimiento_obtenido_mezclado',
  'inicio_almacenamiento',
  'fin_almacenamiento',
  'tiempo_total_almacenamiento',
  'area_tableteo',
  'equipo_tableteo',
  'codigo_tableteo',
  'rendimiento_autorizado_tableteo',
  'rendimiento_obtenido_tableteo'],
 'head': {'no_lote': {0: '4A0001', 1: '4A0002', 2: '4A0003', 3: '4A0004'},
  'area_mezclado': {0: 'Mezclado 1',
   1: 'Mezclado 1',
   2: 'Mezclado 2',
   3: 'Mezclado 1'},
  'equipo_mezclado': {0: 'Mezclador Romboidal',
   1: 'Mezclador Romboidal',
   2: 'Mezclador Romboidal',
   3: 'Mezclador Romboidal'},
  'codigo_mezclado': {0: 'MEZ-007-SL-O',
   1: 'MEZ-007-SL-O',
   2: 'MEZ-006-SL-O',
   3: 'MEZ-007-SL-O'},
  'equipo_molienda': {0: 'Molino Quadro 194 con malla de 1.905 mm',
   1: 'Molino Quadro 194 con malla de 1.905 mm',
   2: 'Molino granulador Hydratec con malla de 1.85 mm',
   3: 'Molino Quadro 194 con malla de 1.905 mm'},
  'codigo_molienda': {0: 'MOL-004-SL-O',
   1: 'MOL-004-SL-O',
   2: 'MOL-002-SL-O',
   3: 'MOL-004-SL-O'},
  'rendimiento_autorizado_mezclado': {0: 100.0, 1: 100.0, 2: 100.0, 3: 100.0},
  'rendimiento_obtenido_mezclado': {0: 101.16, 1: 100.8, 2: 101.33, 3: 101.13},
  'inicio_almacenamiento': {0: '2024-01-05',
   1: '2024-01-05',
   2: '2024-01-05',
   3: '2024-01-05'},
  'fin_almacenamiento': {0: '2024-01-05',
   1: '2024-01-05',
   2: '2024-01-06',
   3: '2024-01-08'},
  'tiempo_total_almacenamiento': {0: '12:55:00',
   1: '9:20:00',
   2: '20:30:00',
   3: '62:30:00'},
  'area_tableteo': {0: 'Tableteo 2',
   1: 'Tableteo 2',
   2: 'Tableteo 2',
   3: 'Tableteo 2'},
  'equipo_tableteo': {0: 'Tableteadora Fette 1200i',
   1: 'Tableteadora Fette 1200i',
   2: 'Tableteadora Fette 1200i',
   3: 'Tableteadora Fette 1200i'},
  'codigo_tableteo': {0: 'TAB-001-SL-O',
   1: 'TAB-001-SL-O',
   2: 'TAB-001-SL-O',
   3: 'TAB-001-SL-O'},
  'rendimiento_autorizado_tableteo': {0: 98.0, 1: 98.0, 2: 98.0, 3: 98.0},
  'rendimiento_obtenido_tableteo': {0: 99.81, 1: 99.34, 2: 99.12, 3: 99.57}}}

In [5]:
#for key, value in available_datasets['antiguedad_de_saldos_mexico_31.07.2024']['head'].items():
large_string = ", \n".join([f"{key}: {value}" for key, value in available_datasets['antiguedad_de_saldos_mexico_31.07.2024']['head'].items()])

print(large_string)

CIA: {0: 10, 1: 10, 2: 10, 3: 10},
TIPO: {0: 3, 1: 3, 2: 3, 3: 3},
CLIENTE: {0: 108123, 1: 108122, 2: 108122, 3: 108118},
NOMBRE_CTE: {0: 'LABORATORIOS PORTUGAL SRL', 1: 'PROBIOMED SA DE CV', 2: 'PROBIOMED SA DE CV', 3: 'PROBIOMED SA DE CV'},
RFC: {0: '201002043330', 1: 'PRO780201IDA', 2: 'PRO780201IDA', 3: 'PRO780201IDA'},
VENDEDOR: {0: 888, 1: 888, 2: 888, 3: 888},
NOMBRE_VENDEDOR: {0: 'VENTA DIRECTA', 1: 'VENTA DIRECTA', 2: 'VENTA DIRECTA', 3: 'VENTA DIRECTA'},
TIPO_DCTO.: {0: 'RI', 1: 'RI', 2: 'RI', 3: 'RI'},
DOCUMENTO: {0: 11444, 1: 230736, 2: 230021, 3: 230737},
PREFIJO: {0: 'SI', 1: '10', 2: '10', 3: '10'},
FECHA_FACTURA: {0: 20231220, 1: 20240730, 2: 20240715, 3: 20240730},
FECHA_VENCIMIENTO: {0: 20240319, 1: 20240829, 2: 20240814, 3: 20240829},
PREFIJO2: {0: 'SI', 1: '10', 2: '10', 3: '10'},
IMPORTE_TRANSACCION: {0: 230000.0, 1: 1076383.6, 2: 21961430.49, 3: 52770.34},
SALDO_TRANSACCION: {0: 137909.99, 1: 1076383.6, 2: 21961430.49, 3: 52770.34},
IMPORTE_MXN: {0: 3892060.0, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
SALDO_MXN: {0: 2333712.85, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
SDO_X_VENC: {0: nan, 1: 1076383.6, 2: 21961430.49, 3: 973480.85},
IMP_1_30: {0: nan, 1: nan, 2: nan, 3: nan},
IMP_31_60: {0: nan, 1: nan, 2: nan, 3: nan},
IMP_61_90: {0: nan, 1: nan, 2: nan, 3: nan},
IMP_91_120: {0: nan, 1: nan, 2: nan, 3: nan},
IM_121_150: {0: 2333712.85, 1: nan, 2: nan, 3: nan},
IMP_361MAS: {0: nan, 1: nan, 2: nan, 3: nan},
UUID: {0: nan, 1: '44B7AEE9-0BFB-9344-AA66-20184E1135B5', 2: '84BC8BA0-5655-6C4B-A010-0184D5757F7C', 3: '01092507-9439-504B-B888-92904711AF16'}

In [17]:
available_functions = AnalystBot.get_available_functions()
keylist = available_functions.keys()
for key in keylist:
    print(key)
display(available_functions)

generate_forecast
generate_forecast_wrapper

{'generate_forecast': {'description': 'Generate time series forecasts and extend the dataframe with predicted values',
  'parameters': {'data': {'type': 'pd.DataFrame',
    'description': 'DataFrame containing time series data',
    'required': True},
   'target_column': {'type': 'str',
    'description': 'Name of the column to forecast',
    'required': True},
   'date_column': {'type': 'str',
    'description': 'Name of the date/time column. If None, first column is used.',
    'required': False,
    'default': None},
   'prediction_length': {'type': 'int',
    'description': 'Number of periods to forecast',
    'required': False,
    'default': 30},
   'forecast_api_url': {'type': 'str',
    'description': 'URL for the forecast API. If None, uses environment variable.',
    'required': False,
    'default': None}},
  'returns': {'type': 'pd.DataFrame',
   'description': 'Extended DataFrame with forecast values and confidence intervals.             The columns in the resulting dataframe are:             target_column:str (the same name as the input, with the forecasted values),             date:str (named as "date", the same dates as the input, with the forecasted dates),             future_assigned:boolean (whether the value is forecasted or not),             lower_quantile:float (the lower quantile of the forecasted values),             upper_quantile:float (the upper quantile of the forecasted values)            '}},
 'generate_forecast_wrapper': {'description': 'Generate time series forecasts and extend the dataframe with predicted values',
  'parameters': {'data': {'type': 'pd.DataFrame',
    'description': 'DataFrame containing time series data',
    'required': True},
   'target_column': {'type': 'str',
    'description': 'Name of the column to forecast',
    'required': True},
   'date_column': {'type': 'str',
    'description': 'Name of the date/time column. If None, first column is used.',
    'required': False,
    'default': None},
   'prediction_length': {'type': 'int',
    'description': 'Number of periods to forecast',
    'required': False,
    'default': 30}},
  'returns': {'type': 'pd.DataFrame',
   'description': 'Extended DataFrame with forecast values and confidence intervals.             The columns in the resulting dataframe are:             target_column:str (the same name as the input, with the forecasted values),             date:str (named as "date", the same dates as the input, with the forecasted dates),             future_assigned:boolean (whether the value is forecasted or not),             lower_quantile:float (the lower quantile of the forecasted values),             upper_quantile:float (the upper quantile of the forecasted values)            '}}}

In [3]:
AnalystBot.safe_globals['generate_forecast_wrapper']

In [4]:
generate_forecast_wrapper = AnalystBot.safe_globals['generate_forecast_wrapper']    

generate_forecast_wrapper.__doc__

'Wrapper for generate_forecast that uses the current forecast client URL'

In [15]:
generate_forecast = AnalystBot.safe_globals['generate_forecast']
import pandas as pd

df = pd.DataFrame({'date': ['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08'],
                    'value': [1, 1, 2, 3, 5, 8, 13, 21]})

forecast = generate_forecast(df, 'value', 'date', 12, forecast_api_url='http://localhost:8000/forecast/')

In [16]:
forecast

,date,value,future_assigned,lower_quantile,upper_quantile
0,2021-01-01 00:00:00+00:00,1.000000,False,NaN,NaN
1,2021-01-02 00:00:00+00:00,1.000000,False,NaN,NaN
2,2021-01-03 00:00:00+00:00,2.000000,False,NaN,NaN
3,2021-01-04 00:00:00+00:00,3.000000,False,NaN,NaN
4,2021-01-05 00:00:00+00:00,5.000000,False,NaN,NaN
5,2021-01-06 00:00:00+00:00,8.000000,False,NaN,NaN
6,2021-01-07 00:00:00+00:00,13.000000,False,NaN,NaN
7,2021-01-08 00:00:00+00:00,21.000000,False,NaN,NaN
8,2021-01-09 00:00:00+00:00,27.611713,True,17.490685,39.385159
9,2021-01-10 00:00:00+00:00,29.160851,True,15.166979,46.201359
10,2021-01-11 00:00:00+00:00,29.264128,True,13.256376,51.158600
11,2021-01-12 00:00:00+00:00,28.851025,True,11.397411,55.496185
12,2021-01-13 00:00:00+00:00,27.508438,True,8.789698,57.768253
13,2021-01-14 00:00:00+00:00,25.856026,True,6.730636,59.214111
14,2021-01-15 00:00:00+00:00,23.893785,True,5.433233,59.627216
15,2021-01-16 00:00:00+00:00,21.724993,True,4.142286,59.007561
16,2021-01-17 00:00:00+00:00,18.265253,True,2.360778,56.322392
17,2021-01-18 00:00:00+00:00,14.805513,True,0.966555,52.604462
18,2021-01-19 00:00:00+00:00,11.294136,True,0.140348,47.647221
19,2021-01-20 00:00:00+00:00,8.815516,True,0.037072,43.309639

In [6]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'date': ['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08'],
                    'value': [1, 1, 2, 3, 5, 8, 13, np.nan]})

In [7]:
df

         date  value
0  2021-01-01    1.0
1  2021-01-02    1.0
2  2021-01-03    2.0
3  2021-01-04    3.0
4  2021-01-05    5.0
5  2021-01-06    8.0
6  2021-01-07   13.0
7  2021-01-08    NaN

In [8]:
df_dict = df.to_dict(orient='records')
df_dict

[{'date': '2021-01-01', 'value': 1.0},
 {'date': '2021-01-02', 'value': 1.0},
 {'date': '2021-01-03', 'value': 2.0},
 {'date': '2021-01-04', 'value': 3.0},
 {'date': '2021-01-05', 'value': 5.0},
 {'date': '2021-01-06', 'value': 8.0},
 {'date': '2021-01-07', 'value': 13.0},
 {'date': '2021-01-08', 'value': nan}]

In [9]:
df_dict_replaced = [{**item, 'value': None if pd.isna(item['value']) else item['value']} for item in df_dict]
df_dict_replaced

[{'date': '2021-01-01', 'value': 1.0},
 {'date': '2021-01-02', 'value': 1.0},
 {'date': '2021-01-03', 'value': 2.0},
 {'date': '2021-01-04', 'value': 3.0},
 {'date': '2021-01-05', 'value': 5.0},
 {'date': '2021-01-06', 'value': 8.0},
 {'date': '2021-01-07', 'value': 13.0},
 {'date': '2021-01-08', 'value': None}]

In [14]:
isinstance(np.nan, type(np.nan))

True

In [15]:
type(np.nan)

float

In [16]:
from datetime import datetime
dt = datetime.now()
print(type(dt))  # datetime.datetime

<class 'datetime.datetime'>

In [17]:
import numpy as np
np_ts = np.datetime64("2024-02-27T12:00:00")
print(type(np_ts))  # numpy.datetime64

<class 'numpy.datetime64'>